[package]
name = "rspm-cli"
version = "0.1.0"
authors = ["Chuck Pierce <cpierce.grad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspm-config = { path = "../config" }
